version: '3.9'

services:
  socket-app:
    build:
      context: ./socket
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    entrypoint:
      -NODE_ENV=production
    networks:
      - app-network

  express-app:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    networks:
      - app-network
    depends_on:
      - postgres

  react-app:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=production
    networks:
      - app-network

  postgres:
    image: postgres:15
    restart: always
    env_file:
      - ./server/.env
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app-network
    ports:
      - "5432:5432"

networks:
  app-network:
    driver: bridge

volumes:
  pgdata: