version: '3.9'

services:
  postgres:
    image: postgres:15
    restart: always
    env_file:
      - ./server/.env
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app-network
    ports:
      - "5432:5432"

volumes:
  pgdata:

networks:
  app-network: